# Generated by Django 5.2.4 on 2025-08-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
